language: bash
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
sudo: required

env:
  global:
    - DOCKER_IMAGE=mcguinness/saml-idp

before_install:
  - tagCommit=`echo ${TRAVIS_COMMIT} | sed "s|/|-|"`
  - export DOCKER_IMAGE_COMMIT=${DOCKER_IMAGE}:${TAG_COMMIT}

script: docker build . -t ${DOCKER_IMAGE_COMMIT}

before_deploy:
  - export DOCKER_IMAGE_TAG=${DOCKER_IMAGE}:${TRAVIS_TAG}
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  - provider: script
    script:
      docker tag ${DOCKER_IMAGE_COMMIT} ${DOCKER_IMAGE_TAG} &&
      docker push ${DOCKER_IMAGE_TAG}
    on:
      tags: true
